(package! gptel)
(package! mips-mode)
(package! go-mode)
(package! deno-fmt)
(package! gameoflife)
(package! sudoku)
(package! plantuml-mode)
(package! agenix)
;; (package! ellsp :recipe :host github :repo "jcs090218/ellsp")
